architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    neoForge {}
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    implementation project(":common")
    include project(":common")
}

version = rootProject.mod_version

processResources {
    def modVersion = project.version
    inputs.property "version", modVersion
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": modVersion
    }
}

tasks.jar {
    manifest {
        attributes "Specification-Title": "golden_chests"
        attributes "Specification-Vendor": "Jeppe Hasseriis"
        attributes "Specification-Version": project.jar.archiveVersion
        attributes "Implementation-Title": project.name
        attributes "Implementation-Version": project.jar.archiveVersion
        attributes "Implementation-Vendor": "Jeppe Hasseriis"
        attributes "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
    }
}
